### PR TITLE
Add offerbook markets

### PR DESCRIPTION
**Pull request by HenrikJannsen**
Based on https://github.com/bisq-network/bisq-mobile/pull/62

### CODE REVIEW

**Comment by rodvar** [comment]
@HenrikJannsen please rebase your branch for review

**Comment by rodvar** [comment]
On a first test, it works great on `androidNode`. For the clients, It's crashing on startup (nio exception) even if I have the rest api on:

```
FATAL EXCEPTION: DefaultDispatcher-worker-3
                                                                                                     Process: network.bisq.mobile.client, PID: 14266
                                                                                                     java.net.ConnectException: Connection refused
                                                                                                     	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
                                                                                                     	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:762)
                                                                                                     	at io.ktor.network.sockets.SocketImpl.connect$ktor_network(SocketImpl.kt:50)
                                                                                                     	at io.ktor.network.sockets.SocketImpl$connect$1.invokeSuspend(Unknown Source:15)
                                                                                                     	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                     	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
                                                                                                     	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:113)
                                                                                                     	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
                                                                                                     	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589)
                                                                                                     	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:823)
                                                                                                     	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720)
                                                                                                     	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707)
                                                                                                     	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContex
```

**Comment by HenrikJannsen** [comment]
> On a first test, it works great on `androidNode`. For the clients, It's crashing on startup (nio exception) even if I have the rest api on:

Just tested again on android and ios and both with for me. Which OS do you use?
You have the lastest main version of bisq2?

**Comment by HenrikJannsen** [comment]
Closed in favor of https://github.com/bisq-network/bisq-mobile/pull/72

**Pull request closed without merging**
