### PR TITLE
Feature/account settings

### PR DESCRIPTION
**Pull request by rodvar**
- 1/2 PRs pf implementation for #51 10a,10b
 - Settings implementation with configurable menu per presenter (allows to configure per app type)
 - Basic implementation with mockup screens
 - navigation of settings fully implemented
 - tested on the 3 apps

### CODE REVIEW

**Comment by rodvar** [comment]
@nostrbuddha please review and let me know if anything needs to be improved for the coming PR

**Comment by nostrbuddha** [comment]
It's a wow. You created a recursive menu structure for the Settings, with breadcrumb navigation as cherry on the cake.
As done by a true master.

Loved this idea <3

Here is one feedback:

    SettingsMenu, SettingsButton, BreadcrumbNavigation

can go into /components/molecules/*

while /uicases/settings/SettingsScreen.kt will have only 'SettingsScreen'

So my idea throughout the app is having only 'Screen' code inside /uicases, while supporting components goes into atoms/molecules/organisms.

**Comment by rodvar** [comment]
> It's a wow. You created a recursive menu structure for the Settings, with breadcrumb navigation as cherry on the cake. As done by a true master.
> 
> Loved this idea <3
> 
> Here is one feedback:
> 
> ```
> SettingsMenu, SettingsButton, BreadcrumbNavigation
> ```
> 
> can go into /components/molecules/*
> 
> while /uicases/settings/SettingsScreen.kt will have only 'SettingsScreen'
> 
> So my idea throughout the app is having only 'Screen' code inside /uicases, while supporting components goes into atoms/molecules/organisms.

Thanks so much for taking some time to review my PR and for your comments buddha 🙏   Means a lot
I agree with your suggestions, this refactor will come in my next PR 💪 💪

**Comment by nostrbuddha** [comment]
Hi Rodvar,
Actually finding 1 another serious problem with this approach now.

Now each nested menu list is not a separate screen, but rather same screen which renders a portion of the menu Tree.
And each parent to child or going back is not real navigation.

So H/w back button and swipe navigations won't fit right here.

To make this work
 * Having dynamic routes in NavGraph like /settings/{path} and handle with navController.navigate('dynamic-nested-paths')
 * (or) keep current code, handle back button / swipe gestures and simulate the navigation in-screen.

**Comment by nostrbuddha** [comment]
Missed one another point yesterday:

The root component in any screen should be BisqStaticLayout or BisqScrollLayout (If you think you will have much contents, so the screen should be scrollable). They just take care of screen edge paddings.

You can replace the root element `Column` with `BisqStaticLayout`

**Comment by rodvar** [comment]
> Missed one another point yesterday:
> 
> The root component in any screen should be BisqStaticLayout or BisqScrollLayout (If you think you will have much contents, so the screen should be scrollable). They just take care of screen edge paddings.
> 
> You can replace the root element `Column` with `BisqStaticLayout`

thanks buddha this is very useful! - I'll add it in my next PR!

**Comment by rodvar** [comment]
> Hi Rodvar, Actually finding 1 another serious problem with this approach.
> 
> Now each nested menu list is not a separate screen, but rather same screen which renders a portion of the menu Tree. And each parent to child or going back is not real navigation.
> 
> So H/w back button and swipe navigations won't fit right here.
> 
> To make this work
> 
> * Having dynamic routes in NavGraph like /settings/{path} and handle with navController.navigate('dynamic-nested-paths')
> * (or) keep current code, handle back button / swipe gestures and simulate the navigation in-screen.
> 
> For MVP, and since we have minimal screens in settings, I prefer we hard code our screens rather than solving with above solutions.
> 
> Let me know :-)

Absolutely right. As you said, for the particular case of Settings I think we can do this exception but we need to handle the navigation better. Ideally as you said, having some kind of deep navigation 'dynamic-nested-path') solved is ideal because we can redirect users to specific settings screens.

one more thing we need as well talking about this is the possibility of blocking back navigation (probably asking the user if they want to exit the app) in certain screens for onboarding (currently you can go back to the splash/bootstrap screen).

I think I'll create issues (or add into existing) for all of this, and in my next PR for `account settings` I'll do the following:

 - Back button/swipe: if screen is showing root settings, normal behaviour, otherwise go one level up in the settings tree.

I'll let you know how I go with this

**Comment by rodvar** [comment]
@nostrbuddha https://github.com/bisq-network/bisq-mobile/issues/109#issuecomment-2544156572

**Comment by rodvar** [comment]
@nostrbuddha further thinking on this, we don't do back navigation between tab menu items and that makes sense. I think it's understandable from a UX perspective how settings has its breadcrum navigation. The breadcrums let you go back to any point you want. Let's discuss further I'll leave it as is (just added a small change: leaf settings is also added to the breadcrums so its more clear where you are at  :) )

**Pull request merged**
