### PR TITLE
Add multiplatform settings

### PR DESCRIPTION
**Pull request by nis-ship-it**
- Added the multiplatform dependency to 3 clients
- Added sample code to test it out

Issue - #39

### CODE REVIEW

**Comment by nis-ship-it** [comment]
At this point, cannot figure out a way to call Settings instance on swift side.

**Comment by rodvar** [comment]
> At this point, cannot figure out a way to call Settings instance on swift side.

hey nish! I'll give you a hand with this tomorrow first thing, may I ask you please to rebase your branch against main first? thanks :pray:

**Comment by rodvar** [comment]
@nis-ship-it hey nish, have a look at my commit above.  (also rebased again for you due to another merge )

The issue is that you are using the `-no-arg` dependency that is not designed to be used outside of common. 

In my commit I linked an implementation of a wrapper of Settings to the proposed PersistanceSource code and its linked to Greetings -> plesae note this makes the app crash on startup (you'll see the "Not implemented" exceptions in the logcat :) )

you can work out your  way from here, you probably want to delete the code you added in iosClient module. Please note also that you pushed unnecesary changes to iosClient + downfgrade of cocoapods again :( we need to figure out what's wrong there :confounded: 

Hope this helps! Let me know if I can help any other way!

**Comment by rodvar** [comment]
@nis-ship-it forgot to mention, not sure if you can push an entire object to settings or there is a way to save a stream string of it? feel free to add other methods or use a different interface if this one doesn't line up with how this lib should be used.

**Comment by rodvar** [comment]
closing in favor of https://github.com/bisq-network/bisq-mobile/pull/76

**Pull request closed without merging**
